---

- include_vars: pepy.yml

- name: Ensure cron variables are set
  cron:
    name: "{{ item.name }}"
    env: yes
    value: "{{ item.value }}"
  with_items:
    - "{{ pepy_env }}"

- name: Ensure update downloads cron exists
  cron:
    name: "update daily downloads"
    minute: "0"
    hour: "17"
    job: "cd {{ project_directory }} && ./venv/bin/python -m pepy import:downloads:day --password \"{{ admin_password_plain }}\""
