---
- name: Install pipenv
  command: pip install pipenv

- name: Install dependencies
  command: pipenv install

- name: Copy bigquery credentials file
  copy:
    src: bigquery_credentials_file.json
    dest: "{{ bigquery_credentials_file }}"
