---
- name: Install pipenv
  command: pip install pipenv

- name: Install dependencies
  command: pipenv install
  environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
  become_user: "{{ gunicorn_user }}"

- name: Copy bigquery credentials file
  copy:
    src: bigquery_credentials_file.json
    dest: "{{ bigquery_credentials_file }}"
