---

- name: Run the migrations
  command: "{{ venv_directory }}/bin/yoyo apply --database \"postgresql://{{ db_user }}:{{ db_password }}@{{ db_host }}/{{ db_name }}\" infrastructure/migrations/"
  args:
    chdir: "{{ project_directory }}"
