---
- name: Ensure postgres is installed
  apt:
    name: ['postgresql', 'libpq-dev', 'python3-psycopg2']
    update_cache: yes

- name: Ensure database is created
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
    state: present

- name: Ensure user has access to database
  become_user: postgres
  postgresql_user: db={{db_name}} name={{db_user}} password={{db_password}} priv=ALL encrypted=yes

- name: Ensure user does not have unnecessary privilege
  become_user: postgres
  postgresql_user: name={{db_user}} role_attr_flags=NOSUPERUSER,NOCREATEDB

- name: Ensure no other user can access the database
  become_user: postgres
  postgresql_privs: db={{db_name}} role=PUBLIC type=database priv=ALL state=absent
